// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGnpfVfjDUZl6yLDhEaODNTTZZ-Y7wE2U',
    appId: '1:1085981803894:android:1c40a08c861ec8b5f7a657',
    messagingSenderId: '1085981803894',
    projectId: 'fir-4-733b3',
    databaseURL: 'https://fir-4-733b3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4-733b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1OixsDjgRvY663pTzI8ONhUCc7M939Gc',
    appId: '1:1085981803894:ios:07c75a5eacaf8bd3f7a657',
    messagingSenderId: '1085981803894',
    projectId: 'fir-4-733b3',
    databaseURL: 'https://fir-4-733b3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4-733b3.appspot.com',
    iosClientId: '1085981803894-ksc53nuufkdqjhabuo7s7j422b8v5g8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.productcloudfirebase',
  );
}
